# Generated by Django 5.1.5 on 2025-01-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.IntegerField(default=50),
        ),
    ]
